/**
 * Re-exports for the design-system surface of instollar-sdk (web).
 * Consumers install only `instollar-sdk` — these packages come as dependencies.
 */

export {
  Button,
  Input,
  Text,
  typography,
  cn,
  ChartCard,
  AreaTrendChart,
  areaTrendChartDemoData,
  DonutChart,
  donutChartDemoData,
  webComponentCatalog,
} from '@instollar-dev/ui-web';
export type {
  ButtonProps,
  ButtonSize,
  ButtonVariant,
  InputProps,
  TextProps,
  TextVariant,
  TypographyClass,
  ChartCardProps,
  AreaTrendChartProps,
  AreaTrendDatum,
  DonutChartProps,
  DonutSlice,
  WebComponentCatalogItem,
  WebComponentCategory,
} from '@instollar-dev/ui-web';

export {
  Icon,
  icons,
  HomeIcon,
  SearchIcon,
  UserIcon,
  ProfileIcon,
  SettingsIcon,
  NotificationIcon,
  MenuIcon,
  MoreIcon,
  CloseIcon,
  AddIcon,
  EditIcon,
  TrashIcon,
  CheckIcon,
  InfoIcon,
  WarningIcon,
  DangerIcon,
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowUpIcon,
  ArrowDownIcon,
  EyeIcon,
  EyeSlashIcon,
  LockIcon,
  UnlockIcon,
  LogoutIcon,
  LoginIcon,
  MessageIcon,
  CallIcon,
  CalendarIcon,
  ClockIcon,
  DocumentIcon,
  DownloadIcon,
  UploadIcon,
  ImageIcon,
  LocationIcon,
  FilterIcon,
  WalletIcon,
  CopyIcon,
  ShareIcon,
  SmsIcon,
  ICON_NAMES,
  isIconName,
} from '@instollar-dev/icons/web';
export type {
  IconProps,
  WebIconProps,
  IconName,
  IconVariant,
  BaseIconProps,
} from '@instollar-dev/icons/web';

export {
  tokens,
  brand,
  colors,
  spacing,
  fontSize,
  fontWeight,
  lineHeight,
  fontFamily,
  cssVariables,
  borderRadius,
  shadow,
} from '@instollar-dev/tokens';
export type { InstollarTokens, InstollarColors, InstollarBrand } from '@instollar-dev/tokens';
